# Generated by Django 5.1.4 on 2025-03-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_customuser_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("EL", "Electronics"),
                    ("FA", "Fashion"),
                    ("BO", "Books"),
                    ("SP", "Sports"),
                    ("OT", "Other"),
                ],
                default="OT",
                max_length=2,
            ),
        ),
    ]
