# Generated by Django 5.1.4 on 2025-03-21 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_group_person_membership_group_members_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                related_query_name="membership",
                to="core.group",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                related_query_name="membership",
                to="core.person",
            ),
        ),
    ]
